/**
 * data.js — Sample BOM data for the On2Cook Device BOM Portal
 * Replace this by uploading your actual Excel file.
 */

/* ─── Sub-assembly definitions ─────────────────────────── */
const SA_META = {
  'O2C-EC-SA-001': 'Electronic Control Assembly',
  'O2C-HT-SA-002': 'Heating & Induction Assembly',
  'O2C-FN-SA-003': 'Fan & Thermal Management',
  'O2C-CS-SA-004': 'Cabinet & Structure Assembly',
};

/* ─── Helper ────────────────────────────────────────────── */
function calcUrgency(days) {
  if (days > 60) return 'critical';
  if (days > 30) return 'high';
  if (days > 13) return 'medium';
  return 'low';
}

/* ─── Sample Parts ──────────────────────────────────────── */
const SAMPLE_BOM = [
  {
    partNumber: 'O2C-EC-001',
    partName: 'Main Control PCB',
    partDesc: 'STM32-based main controller board, 4-layer, integrated power mgmt',
    hsnCode: '85340000',
    partType: 'Electronic Assembly',
    reworkRequired: 'No',
    material: 'FR4 PCB + SMD Components',
    vendorCurrency: 'USD',
    vendorUnitRate: 12.50,
    qty: 1,
    uom: 'PCS',
    totalUnitCost: 1050.00,
    customDuty: 126.00,
    surchargePercent: 10,
    dutyPercent: 18,
    totalFreight: 85.00,
    landedCost: 1340.00,
    supplierName: 'Shenzhen Micro Tech Co.',
    country: 'China',
    leadTimeDays: 75,
    subAssemblies: [
      { id: 'O2C-EC-SA-001', name: 'Electronic Control Assembly', qty: 1 }
    ],
    individualQty: 0,
  },
  {
    partNumber: 'O2C-EC-002',
    partName: 'SMPS Power Module 24V/5A',
    partDesc: '24V DC 5A switching power supply module, flyback topology',
    hsnCode: '85044090',
    partType: 'Electronic Component',
    reworkRequired: 'No',
    material: 'PCB + Transformer + FETs',
    vendorCurrency: 'INR',
    vendorUnitRate: 480.00,
    qty: 1,
    uom: 'PCS',
    totalUnitCost: 480.00,
    customDuty: 0,
    surchargePercent: 0,
    dutyPercent: 5,
    totalFreight: 22.00,
    landedCost: 526.00,
    supplierName: 'Electronica India Pvt. Ltd.',
    country: 'India',
    leadTimeDays: 21,
    subAssemblies: [
      { id: 'O2C-EC-SA-001', name: 'Electronic Control Assembly', qty: 1 }
    ],
    individualQty: 0,
  },
  {
    partNumber: 'O2C-EC-003',
    partName: 'TFT Display 3.5" Module',
    partDesc: '3.5 inch IPS TFT LCD with SPI interface and touchscreen',
    hsnCode: '85285200',
    partType: 'Display Module',
    reworkRequired: 'No',
    material: 'IPS LCD + PCB',
    vendorCurrency: 'USD',
    vendorUnitRate: 6.80,
    qty: 1,
    uom: 'PCS',
    totalUnitCost: 571.20,
    customDuty: 68.54,
    surchargePercent: 10,
    dutyPercent: 18,
    totalFreight: 40.00,
    landedCost: 730.00,
    supplierName: 'Waveshare Electronics',
    country: 'China',
    leadTimeDays: 60,
    subAssemblies: [
      { id: 'O2C-EC-SA-001', name: 'Electronic Control Assembly', qty: 1 }
    ],
    individualQty: 0,
  },
  {
    partNumber: 'O2C-EC-004',
    partName: 'Capacitive Touch Sensor PCB',
    partDesc: 'Multi-zone capacitive touch panel, 6-key layout, I2C interface',
    hsnCode: '85340000',
    partType: 'Sensor PCB',
    reworkRequired: 'Yes',
    material: 'FR4 PCB + ITO Film',
    vendorCurrency: 'USD',
    vendorUnitRate: 3.20,
    qty: 1,
    uom: 'PCS',
    totalUnitCost: 268.80,
    customDuty: 32.26,
    surchargePercent: 10,
    dutyPercent: 18,
    totalFreight: 30.00,
    landedCost: 360.00,
    supplierName: 'Shenzhen Micro Tech Co.',
    country: 'China',
    leadTimeDays: 45,
    subAssemblies: [
      { id: 'O2C-EC-SA-001', name: 'Electronic Control Assembly', qty: 1 }
    ],
    individualQty: 0,
  },
  {
    partNumber: 'O2C-EC-005',
    partName: 'NTC Temperature Sensor 10K',
    partDesc: 'NTC thermistor 10KΩ ±1%, 3950 B-constant, with insulated leads',
    hsnCode: '90251100',
    partType: 'Sensor',
    reworkRequired: 'No',
    material: 'Ceramic + Epoxy Housing',
    vendorCurrency: 'INR',
    vendorUnitRate: 28.00,
    qty: 2,
    uom: 'PCS',
    totalUnitCost: 56.00,
    customDuty: 0,
    surchargePercent: 0,
    dutyPercent: 12,
    totalFreight: 5.00,
    landedCost: 68.72,
    supplierName: 'Sensors & More India',
    country: 'India',
    leadTimeDays: 14,
    subAssemblies: [
      { id: 'O2C-EC-SA-001', name: 'Electronic Control Assembly', qty: 2 }
    ],
    individualQty: 0,
  },
  {
    partNumber: 'O2C-EC-006',
    partName: 'LED Indicator PCB',
    partDesc: 'Status indicator board with 4x RGB LEDs and current limiting resistors',
    hsnCode: '85340000',
    partType: 'Indicator PCB',
    reworkRequired: 'No',
    material: 'FR4 PCB + RGB SMD LEDs',
    vendorCurrency: 'USD',
    vendorUnitRate: 1.80,
    qty: 1,
    uom: 'PCS',
    totalUnitCost: 151.20,
    customDuty: 18.14,
    surchargePercent: 10,
    dutyPercent: 18,
    totalFreight: 20.00,
    landedCost: 210.00,
    supplierName: 'Guangzhou PCB House',
    country: 'China',
    leadTimeDays: 40,
    subAssemblies: [
      { id: 'O2C-EC-SA-001', name: 'Electronic Control Assembly', qty: 1 }
    ],
    individualQty: 0,
  },
  {
    partNumber: 'O2C-HT-001',
    partName: 'Induction Coil Assembly',
    partDesc: 'Litz-wire flat spiral induction coil, 1.8kW rated, ferrite-backed',
    hsnCode: '85044030',
    partType: 'Induction Component',
    reworkRequired: 'Yes',
    material: 'Litz Wire + Ferrite Sheet',
    vendorCurrency: 'USD',
    vendorUnitRate: 18.00,
    qty: 1,
    uom: 'PCS',
    totalUnitCost: 1512.00,
    customDuty: 181.44,
    surchargePercent: 10,
    dutyPercent: 18,
    totalFreight: 120.00,
    landedCost: 1940.00,
    supplierName: 'Zhejiang Coil Systems Ltd.',
    country: 'China',
    leadTimeDays: 90,
    subAssemblies: [
      { id: 'O2C-HT-SA-002', name: 'Heating & Induction Assembly', qty: 1 }
    ],
    individualQty: 0,
  },
  {
    partNumber: 'O2C-HT-002',
    partName: 'IGBT Module IHW30N160R',
    partDesc: 'IGBT transistor 1600V/30A TO-247 package for induction resonant circuit',
    hsnCode: '85411000',
    partType: 'Power Semiconductor',
    reworkRequired: 'No',
    material: 'Silicon Die + TO-247 Package',
    vendorCurrency: 'USD',
    vendorUnitRate: 4.50,
    qty: 2,
    uom: 'PCS',
    totalUnitCost: 756.00,
    customDuty: 90.72,
    surchargePercent: 10,
    dutyPercent: 18,
    totalFreight: 35.00,
    landedCost: 960.00,
    supplierName: 'Infineon Distributor SZ',
    country: 'China',
    leadTimeDays: 60,
    subAssemblies: [
      { id: 'O2C-HT-SA-002', name: 'Heating & Induction Assembly', qty: 2 }
    ],
    individualQty: 0,
  },
  {
    partNumber: 'O2C-HT-003',
    partName: 'Ferrite Core EE55 Set',
    partDesc: 'EE55/28/21 ferrite core pair, PC40 material, for resonant transformer',
    hsnCode: '85050000',
    partType: 'Magnetic Component',
    reworkRequired: 'No',
    material: 'MnZn Ferrite PC40',
    vendorCurrency: 'USD',
    vendorUnitRate: 2.20,
    qty: 4,
    uom: 'SET',
    totalUnitCost: 739.20,
    customDuty: 88.70,
    surchargePercent: 10,
    dutyPercent: 18,
    totalFreight: 28.00,
    landedCost: 930.00,
    supplierName: 'Magnetics China Ltd.',
    country: 'China',
    leadTimeDays: 30,
    subAssemblies: [
      { id: 'O2C-HT-SA-002', name: 'Heating & Induction Assembly', qty: 4 }
    ],
    individualQty: 0,
  },
  {
    partNumber: 'O2C-HT-004',
    partName: 'Thermal Interface Pad 1mm',
    partDesc: 'Silicone thermal pad 100x100mm 1mm thick, 6W/mK conductivity',
    hsnCode: '39100000',
    partType: 'Thermal Material',
    reworkRequired: 'No',
    material: 'Silicone + Aluminium Oxide Filler',
    vendorCurrency: 'INR',
    vendorUnitRate: 65.00,
    qty: 2,
    uom: 'PCS',
    totalUnitCost: 130.00,
    customDuty: 0,
    surchargePercent: 0,
    dutyPercent: 12,
    totalFreight: 8.00,
    landedCost: 153.60,
    supplierName: 'Thermotech Solutions',
    country: 'India',
    leadTimeDays: 7,
    subAssemblies: [
      { id: 'O2C-HT-SA-002', name: 'Heating & Induction Assembly', qty: 2 }
    ],
    individualQty: 0,
  },
  {
    partNumber: 'O2C-FN-001',
    partName: 'DC Brushless Fan 120mm',
    partDesc: '120x120x25mm DC 24V brushless fan, 1800 RPM, PWM controlled',
    hsnCode: '84145930',
    partType: 'Cooling Component',
    reworkRequired: 'No',
    material: 'PBT Blades + Motor Assembly',
    vendorCurrency: 'USD',
    vendorUnitRate: 3.50,
    qty: 2,
    uom: 'PCS',
    totalUnitCost: 588.00,
    customDuty: 70.56,
    surchargePercent: 10,
    dutyPercent: 18,
    totalFreight: 32.00,
    landedCost: 760.00,
    supplierName: 'Delta Fan Components',
    country: 'China',
    leadTimeDays: 35,
    subAssemblies: [
      { id: 'O2C-FN-SA-003', name: 'Fan & Thermal Management', qty: 2 }
    ],
    individualQty: 0,
  },
  {
    partNumber: 'O2C-FN-002',
    partName: 'Fan Guard Grill 120mm',
    partDesc: 'Wire guard grill for 120mm fan, zinc-plated steel, with mounting screws',
    hsnCode: '73269090',
    partType: 'Mechanical',
    reworkRequired: 'No',
    material: 'Galvanised Steel Wire',
    vendorCurrency: 'INR',
    vendorUnitRate: 38.00,
    qty: 2,
    uom: 'PCS',
    totalUnitCost: 76.00,
    customDuty: 0,
    surchargePercent: 0,
    dutyPercent: 12,
    totalFreight: 6.00,
    landedCost: 91.12,
    supplierName: 'Pune Metal Works',
    country: 'India',
    leadTimeDays: 10,
    subAssemblies: [
      { id: 'O2C-FN-SA-003', name: 'Fan & Thermal Management', qty: 2 }
    ],
    individualQty: 0,
  },
  {
    partNumber: 'O2C-FN-003',
    partName: 'Thermal Fuse 130°C 10A',
    partDesc: 'One-shot thermal cutoff fuse, 130°C rated, axial lead, 250V/10A',
    hsnCode: '85361000',
    partType: 'Safety Component',
    reworkRequired: 'No',
    material: 'Bimetal + Ceramic Housing',
    vendorCurrency: 'INR',
    vendorUnitRate: 22.00,
    qty: 1,
    uom: 'PCS',
    totalUnitCost: 22.00,
    customDuty: 0,
    surchargePercent: 0,
    dutyPercent: 12,
    totalFreight: 4.00,
    landedCost: 28.64,
    supplierName: 'Electronica India Pvt. Ltd.',
    country: 'India',
    leadTimeDays: 14,
    subAssemblies: [
      { id: 'O2C-FN-SA-003', name: 'Fan & Thermal Management', qty: 1 }
    ],
    individualQty: 0,
  },
  {
    partNumber: 'O2C-FN-004',
    partName: 'Fan Mounting Bracket',
    partDesc: 'Sheet metal bracket for dual 120mm fan mounting with vibration dampeners',
    hsnCode: '73089090',
    partType: 'Sheet Metal',
    reworkRequired: 'No',
    material: 'CRCA Steel 1.2mm',
    vendorCurrency: 'INR',
    vendorUnitRate: 95.00,
    qty: 1,
    uom: 'PCS',
    totalUnitCost: 95.00,
    customDuty: 0,
    surchargePercent: 0,
    dutyPercent: 18,
    totalFreight: 10.00,
    landedCost: 117.10,
    supplierName: 'Ahmedabad Fabricators',
    country: 'India',
    leadTimeDays: 10,
    subAssemblies: [
      { id: 'O2C-FN-SA-003', name: 'Fan & Thermal Management', qty: 1 }
    ],
    individualQty: 0,
  },
  {
    partNumber: 'O2C-CS-001',
    partName: 'Top Cover Panel',
    partDesc: 'Powder-coated CRCA top panel with ventilation slots and branding cutout',
    hsnCode: '73089090',
    partType: 'Sheet Metal',
    reworkRequired: 'No',
    material: 'CRCA Steel 1.5mm + Powder Coat',
    vendorCurrency: 'INR',
    vendorUnitRate: 420.00,
    qty: 1,
    uom: 'PCS',
    totalUnitCost: 420.00,
    customDuty: 0,
    surchargePercent: 0,
    dutyPercent: 18,
    totalFreight: 30.00,
    landedCost: 525.60,
    supplierName: 'Ahmedabad Fabricators',
    country: 'India',
    leadTimeDays: 15,
    subAssemblies: [
      { id: 'O2C-CS-SA-004', name: 'Cabinet & Structure Assembly', qty: 1 }
    ],
    individualQty: 0,
  },
  {
    partNumber: 'O2C-CS-002',
    partName: 'Bottom Base Frame',
    partDesc: 'Reinforced base frame with PCB mounting pillars and rubber feet slots',
    hsnCode: '73089090',
    partType: 'Sheet Metal',
    reworkRequired: 'No',
    material: 'CRCA Steel 2.0mm + Powder Coat',
    vendorCurrency: 'INR',
    vendorUnitRate: 560.00,
    qty: 1,
    uom: 'PCS',
    totalUnitCost: 560.00,
    customDuty: 0,
    surchargePercent: 0,
    dutyPercent: 18,
    totalFreight: 35.00,
    landedCost: 696.80,
    supplierName: 'Ahmedabad Fabricators',
    country: 'India',
    leadTimeDays: 20,
    subAssemblies: [
      { id: 'O2C-CS-SA-004', name: 'Cabinet & Structure Assembly', qty: 1 }
    ],
    individualQty: 0,
  },
  {
    partNumber: 'O2C-CS-003',
    partName: 'Side Panel Left',
    partDesc: 'Left side cabinet panel, powder-coated, with cable management slots',
    hsnCode: '73089090',
    partType: 'Sheet Metal',
    reworkRequired: 'No',
    material: 'CRCA Steel 1.5mm + Powder Coat',
    vendorCurrency: 'INR',
    vendorUnitRate: 280.00,
    qty: 1,
    uom: 'PCS',
    totalUnitCost: 280.00,
    customDuty: 0,
    surchargePercent: 0,
    dutyPercent: 18,
    totalFreight: 22.00,
    landedCost: 352.40,
    supplierName: 'Ahmedabad Fabricators',
    country: 'India',
    leadTimeDays: 20,
    subAssemblies: [
      { id: 'O2C-CS-SA-004', name: 'Cabinet & Structure Assembly', qty: 1 }
    ],
    individualQty: 0,
  },
  {
    partNumber: 'O2C-CS-004',
    partName: 'Side Panel Right',
    partDesc: 'Right side cabinet panel, powder-coated, mirror of left panel',
    hsnCode: '73089090',
    partType: 'Sheet Metal',
    reworkRequired: 'No',
    material: 'CRCA Steel 1.5mm + Powder Coat',
    vendorCurrency: 'INR',
    vendorUnitRate: 280.00,
    qty: 1,
    uom: 'PCS',
    totalUnitCost: 280.00,
    customDuty: 0,
    surchargePercent: 0,
    dutyPercent: 18,
    totalFreight: 22.00,
    landedCost: 352.40,
    supplierName: 'Ahmedabad Fabricators',
    country: 'India',
    leadTimeDays: 20,
    subAssemblies: [
      { id: 'O2C-CS-SA-004', name: 'Cabinet & Structure Assembly', qty: 1 }
    ],
    individualQty: 0,
  },
  {
    partNumber: 'O2C-CS-005',
    partName: 'Control Knob Assembly',
    partDesc: 'Rotary encoder + ABS knob + snap-fit bezel, click-detent tactile feel',
    hsnCode: '85369090',
    partType: 'Electromechanical',
    reworkRequired: 'No',
    material: 'ABS + Aluminium Knob',
    vendorCurrency: 'INR',
    vendorUnitRate: 145.00,
    qty: 1,
    uom: 'PCS',
    totalUnitCost: 145.00,
    customDuty: 0,
    surchargePercent: 0,
    dutyPercent: 12,
    totalFreight: 8.00,
    landedCost: 170.40,
    supplierName: 'Mumbai Switch Mart',
    country: 'India',
    leadTimeDays: 25,
    subAssemblies: [
      { id: 'O2C-CS-SA-004', name: 'Cabinet & Structure Assembly', qty: 1 }
    ],
    individualQty: 0,
  },
  {
    partNumber: 'O2C-HW-001',
    partName: 'M3×8 SS Hex Screw',
    partDesc: 'M3×8mm stainless steel hex socket head cap screw, grade A2-70',
    hsnCode: '73181500',
    partType: 'Hardware / Fastener',
    reworkRequired: 'No',
    material: 'SS 304',
    vendorCurrency: 'INR',
    vendorUnitRate: 1.80,
    qty: 34,
    uom: 'PCS',
    totalUnitCost: 61.20,
    customDuty: 0,
    surchargePercent: 0,
    dutyPercent: 12,
    totalFreight: 3.00,
    landedCost: 71.54,
    supplierName: 'Fastener Hub India',
    country: 'India',
    leadTimeDays: 5,
    subAssemblies: [
      { id: 'O2C-EC-SA-001', name: 'Electronic Control Assembly', qty: 8 },
      { id: 'O2C-HT-SA-002', name: 'Heating & Induction Assembly', qty: 6 },
      { id: 'O2C-FN-SA-003', name: 'Fan & Thermal Management', qty: 8 },
      { id: 'O2C-CS-SA-004', name: 'Cabinet & Structure Assembly', qty: 12 },
    ],
    individualQty: 0,
  },
  {
    partNumber: 'O2C-HW-002',
    partName: 'M4×12 SS Hex Screw',
    partDesc: 'M4×12mm stainless steel hex socket head cap screw, grade A2-70',
    hsnCode: '73181500',
    partType: 'Hardware / Fastener',
    reworkRequired: 'No',
    material: 'SS 304',
    vendorCurrency: 'INR',
    vendorUnitRate: 2.40,
    qty: 18,
    uom: 'PCS',
    totalUnitCost: 43.20,
    customDuty: 0,
    surchargePercent: 0,
    dutyPercent: 12,
    totalFreight: 2.50,
    landedCost: 50.89,
    supplierName: 'Fastener Hub India',
    country: 'India',
    leadTimeDays: 5,
    subAssemblies: [
      { id: 'O2C-EC-SA-001', name: 'Electronic Control Assembly', qty: 4 },
      { id: 'O2C-FN-SA-003', name: 'Fan & Thermal Management', qty: 6 },
      { id: 'O2C-CS-SA-004', name: 'Cabinet & Structure Assembly', qty: 8 },
    ],
    individualQty: 0,
  },
  {
    partNumber: 'O2C-CB-001',
    partName: 'Power Cable Assembly 1.5m',
    partDesc: '3-pin ISI marked power cord 1.5m, 3×1.5mm² copper, with moulded plug',
    hsnCode: '85444290',
    partType: 'Cable Assembly',
    reworkRequired: 'No',
    material: 'PVC + Copper Conductor',
    vendorCurrency: 'INR',
    vendorUnitRate: 85.00,
    qty: 1,
    uom: 'PCS',
    totalUnitCost: 85.00,
    customDuty: 0,
    surchargePercent: 0,
    dutyPercent: 12,
    totalFreight: 5.00,
    landedCost: 100.20,
    supplierName: 'Polycab Wires Ltd.',
    country: 'India',
    leadTimeDays: 12,
    subAssemblies: [],
    individualQty: 1,
  },
];

/* ─── Attach urgency flags ──────────────────────────────── */
SAMPLE_BOM.forEach(p => {
  p.urgency = calcUrgency(p.leadTimeDays);
});